
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async isFirstRun() : Promise<boolean> {
    return await TAURI_INVOKE("is_first_run");
},
async getSettings() : Promise<Settings> {
    return await TAURI_INVOKE("get_settings");
},
async updateSettings(settings: Settings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModels() : Promise<ModelInfo[]> {
    return await TAURI_INVOKE("get_models");
},
async downloadModel(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGpuBackend() : Promise<string> {
    return await TAURI_INVOKE("get_gpu_backend");
},
async resizeWindow(height: number) : Promise<void> {
    await TAURI_INVOKE("resize_window", { height });
},
async resetApp() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_app") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMonitors() : Promise<MonitorInfo[]> {
    return await TAURI_INVOKE("get_monitors");
},
async getMemoryInfo(gpu: boolean) : Promise<MemoryInfo> {
    return await TAURI_INVOKE("get_memory_info", { gpu });
},
async getInputDevices() : Promise<InputDeviceInfo[]> {
    return await TAURI_INVOKE("get_input_devices");
},
async transcribeFile(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistory() : Promise<HistoryEntry[]> {
    return await TAURI_INVOKE("get_history");
},
async clearHistory() : Promise<void> {
    await TAURI_INVOKE("clear_history");
},
async deleteHistoryEntry(id: number) : Promise<void> {
    await TAURI_INVOKE("delete_history_entry", { id });
},
async showLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openUrl(url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_url", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async quit() : Promise<void> {
    await TAURI_INVOKE("quit");
},
async checkForUpdate() : Promise<UpdateInfo> {
    return await TAURI_INVOKE("check_for_update");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type DownloadProgress = { model: string; downloaded: number; total: number }
export type HistoryEntry = { id: number; timestamp: number; text: string; source: string }
export type InputDeviceInfo = { name: string; label: string }
export type MemoryInfo = { total_mb: number; available_mb: number }
export type ModelInfo = { name: string; size_mb: number; downloaded: boolean }
export type ModelLoading = "eager" | "lazy" | "per_use"
export type MonitorInfo = { index: number; name: string; width: number; height: number; primary: boolean }
export type OutputMode = "clipboard" | "paste"
export type OverlayPosition = "top-left" | "top-center" | "top-right" | "bottom-left" | "bottom-center" | "bottom-right"
export type OverlaySize = "small" | "medium" | "large"
export type OverlayState = { status: OverlayStatus; ttl_ms: number | null }
export type OverlayStatus = "idle" | "recording" | "processing" | "loading" | "saved" | "copied" | "typed" | "deleted" | "cancelled" | "output_mode"
export type Settings = { model: string; output_mode: OutputMode; hotkey: string; language?: string; gpu?: boolean; interrupt?: boolean; output_hotkey?: string; min_duration?: number; overlay_enabled?: boolean; overlay_position?: OverlayPosition; overlay_size?: OverlaySize; overlay_monitor?: number; overlay_always_show?: boolean; input_device?: string; model_loading?: ModelLoading; autostart?: boolean; history_enabled?: boolean; history_retention?: number }
export type UpdateInfo = { available: boolean; current: string; latest: string; url: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
